Roster/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    #path('', views.roster_home, name="roster-default" ),
    #path('', views.PersonView.as_view(), name="person-list" ),
    path('', views.roster_home.as_view(), name="roster-home" ),
    path('people', views.roster_home.as_view(), name="roster-home" ),
    path('people/list', views.load_people, name="roster-load-people"),
    path('people/create/', views.CreatePerson.as_view(), name="person-create" ),
    path('people/<slug:slug>/', views.UpdatePerson.as_view(), name='person-edit'),
    path('people/delete/<slug:slug>/', views.DeletePerson.as_view(), name='person-delete'),
]

StatusApp/urls.py
from django.urls import path, include

from . import views
app_name = 'status'
urlpatterns = [
    path('', views.GroupListView.as_view(), name="group_list"),
    path('group/', views.GroupListView.as_view(), name="sb-default" ),
    path('group/<slug:slug>/', views.GroupMembersList, name="sb-group-view" ),
    path('group/<slug:slug>/mod/<slug:user>/<str:action>', views.GroupCRUD, name="sb-group-crud" ),
    path('group/<slug:slug>/mod', views.GroupModView, name="sb-group-mod" ),
    path('group/<slug:slug>/user/search', views.UserSearch, name="user-search"),
    path('group/add/', views.CreateGroup, name='sb-group-create'),
    path('userstatus/modal/<slug:slug>', views.UserStatusModal, name="user-modal"),
    path('members/<slug:slug>/', views.LoadGroupMembers, name="sb-group-members" ),

 ]

centraloffice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('status/', include('StatusApp.urls'),),
    path('people/', include('Roster.urls'),),
]

StatusApp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify
BOOTSTRAP_BUTTON_CHOICES = (
   ( "btn-primary", "Primary"),
   ( "btn-secondary", "Secondary"),
   ( "btn-success", "Success"),
   ( "btn-danger", "Danger"),
   ( "btn-warning", "Warning"),
   ( "btn-info", "Infomation"),
   ( "btn-light", "Light"),
   ( "btn-dark", "Dark"),
   ( "btn-link", "Link"),
)

User = get_user_model()




class Status(models.Model):
    name = models.CharField(max_length=50)
    css = models.CharField(max_length=15,
                  choices=BOOTSTRAP_BUTTON_CHOICES,
                  )
    slug = models.SlugField(unique=True, blank=True)
    class Meta:
        verbose_name_plural = "Status"
        verbose_name = "Status"
        db_table = "status"
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    def __str__(self):
        return f"{self.name}"




class UserStatus(models.Model):
    class Meta:
        verbose_name_plural = "UserStatus"
        verbose_name = "UserStatus"
        db_table = "User_status"
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="status")
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    lock_status = models.BooleanField(default=False)
    lock_notes = models.BooleanField(default=False)
    notes = models.CharField(max_length=100, blank=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, blank=True)
    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super().save(*args, **kwargs)
    def __str__(self):
        return f"{self.user}"

class Group(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100, blank=True)
    members = models.ManyToManyField(UserStatus, related_name="member_of", blank=True)
    mods = models.ManyToManyField(UserStatus, related_name="moderating", blank=True)
    slug = models.SlugField(unique=True, blank=True)
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    def __str__(self):
        return f"{self.name}"

StatusApp/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit,HTML, Layout, Field, Row, Column
from crispy_forms.bootstrap import FormActions
from . import models


class GroupForm(forms.ModelForm):
    class Meta:
        model = models.Group
        fields = [ 'name', 'description' ]
    layout = Layout(
        'name',
        'description',
        FormActions(
            Submit('submit', 'Submit', css_class='btn btn-sm'),
            #HTML('<a href="{% url "sb-default" %}" class="btn btn-sm btn-link">Cancel</a>'),
        )
    )
    helper = FormHelper()
    helper.layout = layout

class UserStatusForm(forms.ModelForm):
    
    class Meta:
        model = models.UserStatus
        fields = '__all__'
        exclude = ['user', 'slug']
        labels = {
            'lock_status': 'Lock Status',
            'lock_notes': "Lock Notes",
        }
    layout = Layout(
        Row(
            
            
            Column('status', css_class="col-1"),
            Column('notes', css_class="col-8"),
            Column('lock_status','lock_notes',  css_class="col"),
            Column(
                HTML('<label for="submit-id-submit" class="form-label"></label>'),
                FormActions(
                  
                  Submit('submit', 'Update', css_class='btn btn-danger')
                  , css_class="col-1"
                  ),
                  HTML('<a href="{% url "home" %}" class="btn btn-sm btn-link">Cancel</a>')
            ),
            
            css_class="row text-start mb-2"
            ),
        
    )
    helper = FormHelper()
    helper.layout = layout

StatusApp/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.contrib.auth import get_user_model
from django_tables2.views import SingleTableMixin, SingleTableView
from django_filters.views import FilterView
from django.views.generic import CreateView, DetailView
from django.urls import reverse_lazy
from django.db.models import Q
from django.shortcuts import render

from . import tables, filters, models, forms
# Create your views here.

def main_page(request):
    if request.user.is_authenticated:
        return redirect('/status/')
    else:
        return redirect('/accounts/login')

def GroupMembersList(request, slug):
    group = models.Group.objects.get(slug=slug)
    #members = group.members.order_by('user__last_name').all()
    current_user_slug = request.user.slug
    current_user = get_object_or_404(models.UserStatus, slug=current_user_slug)
    is_a_mod = False
    if current_user in group.mods.all():
        is_a_mod = True
    context = { 'group': group,
                'is_a_mod': is_a_mod,
     #           'members': members
               }
    return render(request, "StatusApp/grouplist.html", context=context)


def LoadGroupMembers(request, slug):
    group = models.Group.objects.get(slug=slug)
    members = group.members.order_by('user__last_name').all()
    context = { 
               'group': group,
               'members': members
               }
    return render(request, "StatusApp/partials/group_members.html", context=context)


def GroupModView(request, slug):
    group = models.Group.objects.get(slug=slug)
    current_user_slug = request.user.slug
    current_user = get_object_or_404(models.UserStatus, slug=current_user_slug)
    members = group.members.order_by('user__last_name').all()
    is_a_mod = False
    if current_user in group.mods.all():
        is_a_mod = True
    if not is_a_mod:
        return redirect('/status/')


    context = { 'group': group,
                'is_a_mod': is_a_mod,
                'members': members
               }
    return render(request, "StatusApp/group_admin.html", context=context)
def UserStatusModal(request, slug):
    user = models.UserStatus.objects.get(slug=slug)
    if request.method == "POST":
        form = forms.UserStatusForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            #return HttpResponse(status=204)
            response = HttpResponse(status=200)
            response['HX-Refresh'] = 'true'
            return response
    form = forms.UserStatusForm(instance=user)
    context = { 'user': user,
               'form': form}
    return render(request, "StatusApp/status_modal.html", context)
def CreateGroup(request, user_slug):
    if request.user.slug:
        current_user = models.UserStatus(slug=request.user.slug)
        group_name = request.GET.get('group', '')
        if group_name:
         new_group = models.Group(name=group_name)
         new_group.mods.add(current_user)
         new_group.members.add(current_user)
         new_group.save()
         GroupModView(request, new_group.slug)
         
    else:
        return redirect('/status/')
    
def GroupCRUD(request, slug, user, action):
    group = models.Group.objects.get(slug=slug)
    current_user_slug = request.user.slug
    current_user = get_object_or_404(models.UserStatus, slug=current_user_slug)
    user_object = get_object_or_404(models.UserStatus, slug=user)
    is_a_mod = False
    if current_user in group.mods.all():
        is_a_mod = True
    if not is_a_mod:
        return redirect('/status/')

    admin_mode=True
    context = { 'group': group,
                'is_a_mod': is_a_mod,
                'admin_mode': admin_mode,

               }
    members = group.members.order_by('user__last_name').all()
    context['members'] = members
    match action:
        case "admin_mode":
            return render(request, "StatusApp/partials/group_members.html", context)

        case "addmember":
            group.members.add(user_object)
            group = models.Group.objects.get(slug=slug)
            members = group.members.order_by('user__last_name').all()
            context['members'] = members
            return render(request, "StatusApp/partials/group_members.html", context)

        case "deletemember":
            group.members.remove(user_object)
            group = models.Group.objects.get(slug=slug)
            members = group.members.order_by('user__last_name').all()
            context['members'] = members
            return render(request, "StatusApp/partials/group_members.html", context)

        case "addmod":
            group.mods.add(user_object)
            group = models.Group.objects.get(slug=slug)
            members = group.members.order_by('user__last_name').all()
            return render(request, "StatusApp/partials/group_members.html", context)
        
        case "deletemod":
            group.mods.remove(user_object)
            group = models.Group.objects.get(slug=slug)
            members = group.members.order_by('user__last_name').all()
            return render(request, "StatusApp/partials/group_members.html", context)

        case _:
            return redirect('/status/')
    return redirect('/status/')

def UserSearch(request, slug):
    group = models.Group.objects.get(slug=slug)
    context = {'group': group}
    searchstr = request.GET.get('search', '')
    users = ''
    if searchstr:
        users = models.UserStatus.objects.filter(Q(user__first_name__icontains=searchstr) |
                                                 Q(user__username__icontains=searchstr) |
                                                 Q(user__last_name__icontains=searchstr)
                                                   ).distinct().exclude(member_of=group)
    print("---")
    for u in users:
        print(u)
    print("---")
    context['users'] = users
    
    return render(request, "StatusApp/partials/search.html", context)



def UpdateUserStatus(request, user_slug, status_slug ):
    user = get_object_or_404(models.UserStatus, slug=user_slug)
    status = get_object_or_404(models.Status, slug=status_slug)
    user.status = status
    user.save()
    return HttpResponse(status=204)

    pass
    #user = models.UserStatus.get(slug=user_slug)



class GroupListView(SingleTableMixin, FilterView):
    model = models.Group
    template_name = "StatusApp/sb_filter.html"
    table_class = tables.GroupTable
    filterset_class = filters.GroupFilter
    table_pagination = {
        "per_page": 25,
    }

class GroupView(SingleTableMixin, DetailView):
    model = models.Group
    template_name = "StatusApp/sb_group.html"
    table_class = tables.GroupTable
    form_class = forms.GroupForm

StatusApp/templates/StatusApp/group_admin.html
{% extends "sb_base.html" %}
{% load django_tables2 %}
{% load django_bootstrap5 %}
{% load bootstrap_icons %}
{% load crispy_forms_tags %}
{%block title%}{{ group }}{%endblock%}



  {%block content%}
<center>
  <h2> <a href="{% url 'status:sb-group-view' slug=group.slug %}">{{ group }}</a> </h2> 
{% if group.description %}
<p> [{{ group.description }}] <p>
{%endif%}


<!--Members table-->
<div class="container-fluid text-start border-bottom">
  <!--Members header-->
  <div class="row mb-2">
    <div class="col-2">Name</div>
    <div class="col-1">Status</div>
    <div class="col-6">Notes</div>
    <div class="col-3">Updated</div>
  </div>
  
  
</div>
  <!--End Header-->
<div id="group_members" hx-trigger="load" hx-get="{% url "status:sb-group-crud" user=user.slug slug=group.slug action="admin_mode" %}">


</div>
  



{% if is_a_mod %}
  <div class="row mb-2" id="edit_mode">
    <div class="col-2"></div>
    <div class="col-1"></div>
    <div class="col-6"></div>
    <div class="col-3"><a href="{% url 'status:sb-group-view' slug=group.slug %}"
      {% bs_icon 'box-arrow-left' size='2em'%}</a>
    </div>
  </div>
<div class="row mb-2" id="add_person">
    <div class="col-2">
    </div>
    <div class="col-1">Add Person</div>
    <div class="col-6">
        <input class="form-control"
               id="searchbar"
               name="search"
               placeholder="Start Typing to Search"
               hx-target="#person_search",
               hx-get="{% url 'status:user-search' slug=group.slug %}"
               hx-trigger="input changed delay:500ms, keyword">
    </div>
    <div class="col-3"></a>
    </div>
   
</div>
<div id="person_search" class="row mb-2">
</div>
</div> <!--End member table-->

{%else%}
Moderators:

{%for mod in group.mods.all %}
{{ mod }} <p>
{%endfor%}
{%endif%}

  {%endblock%}
  

StatusApp/templates/StatusApp/grouplist.html
{% extends "sb_base.html" %}
{% load django_tables2 %}
{% load django_bootstrap5 %}
{% load bootstrap_icons %}
{% load crispy_forms_tags %}
{%block title%}{{ group }}{%endblock%}



  {%block content%}
<center>
  <h2> <a href="{% url 'status:sb-group-view' slug=group.slug %}">{{ group }}</a> </h2>
{% if group.description %}
<p> [{{ group.description }}] <p>
{%endif%}


<!--Members table-->
<div class="container-fluid text-start border-bottom">
  <!--Members header-->
  <div class="row mb-2">
    <div class="col-2">Name</div>
    <div class="col-1">Status</div>
    <div class="col-6">Notes</div>
    <div class="col-3">Updated</div>
  </div>
  
  
</div>
  <!--End Header-->
<div id="group_members" hx-trigger="load" hx-get="{% url "status:sb-group-members" slug=group.slug %}">


</div>
  



{% if is_a_mod %}
  <div class="row mb-2" id="edit_mode">
    <div class="col-2"></div>
    <div class="col-1"></div>
    <div class="col-6"></div>
    <div class="col-3"><a href="{% url 'status:sb-group-mod' slug=group.slug %}"
      >{% bs_icon 'pencil-fill' size='2em'%}</a>
    </div>
  </div>

</div> <!--End member table-->

{%else%}
Moderators:

{%for mod in group.mods.all %}
{{ mod }} <p>
{%endfor%}
{%endif%}

  {%endblock%}
  

StatusApp/templates/StatusApp/sb_filter.html
{% extends "sb_base.html" %}
{% load django_tables2 %}
{% load django_bootstrap5 %}
{% load bootstrap_icons %}
{%block title%}{%endblock%}



  {%block crud%}

    {% render_table table 'django_tables2/bootstrap5.html' %}
    {% if user.is_staff %}






    {%endif%}
  {%endblock%}
  {%block filter_block%}
  {% if filter %}
          Filters<p>
            <form action="" method="get" class="form form-inline">
              {% bootstrap_form filter.form layout='inline' %}
              {% bootstrap_button 'Filter' %}
            </form>
        {%endif %}
  {%endblock%}

StatusApp/templates/StatusApp/sb_form.html
{% extends "sb_base.html" %}
{% load crispy_forms_tags %}
{% load django_tables2 %}
{% load django_bootstrap5 %}

{%block title%}
{% if group %}Edit {{group}}{% else %}Create a New Entry{% endif %}
{%endblock%}
{%block crud%}

{%if form %}
  <form method="POST" {% if form.is_multipart %}enctype="multipart/form-data" {% endif %}
    action="{% if object %}{{ update_view_url }}{% else %}{{ create_view_url }}{% endif %}">
    {% csrf_token %}
    {% crispy form %}
  </form>
{%else%}
  NO FORM FOUND!?!?!
{%endif%}

{%endblock%}

StatusApp/templates/StatusApp/sb_group.html
{% extends "sb_base.html" %}
{% load django_tables2 %}
{% load django_bootstrap5 %}
{%block title%}{%endblock%}



  {%block crud%}

    {% render_table table 'django_tables2/bootstrap5.html' %}

  {%endblock%}
  {%block filter_block%}
  {% if filter %}
          Filters<p>
            <form action="" method="get" class="form form-inline">
              {% bootstrap_form filter.form layout='inline' %}
              {% bootstrap_button 'Filter' %}
            </form>
        {%endif %}
  {%endblock%}

StatusApp/templates/StatusApp/status_modal.html
{% load django_tables2 %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}

<form
      hx-post={% url 'status:user-modal' slug=user.slug%} 
      hx-swap=none
      hx-on:htmx:after-request="
        if (event.detail.xhr.status === 204)
          bootstrap.Modal.getInstance('#set_status').hide()
      ">
<div class="modal-dialog">
    <div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title">Update Status</h5>
  </div>
  <div class="modal-body">

      {% csrf_token %}
    {{ form|crispy }}

  </div>
  <div class="modal-footer">
    <button type="button" data-bs-dismiss="modal">Cancel</button>
    <button type="submit">Save</button>
  </div>
</div>
</div>

</form>